#!/usr/bin/env python3
"""Table 3: post-route resource utilisation and timing, real Vivado reports,
all three kernels (all with the m_axi fix). Source:
evidence/synthesis/{shor,steane,rep3}_m_axi_fix_postroute_2026-08-20/.
Usage: python3 gen_table3.py > table3_postroute.tex
"""

ROWS = [
    ("Rep-3", 0, 0, 1209, 985, 241, "+0.003"),
    ("Shor", 0, 0, 1245, 1018, 295, "+0.003"),
    ("Steane (x3)", 0, 0, 1286, 1067, 283, "+0.003"),
]

print(r"% Auto-generated by paper/tables/gen_table3.py -- do not hand-edit.")
print(r"% Source: evidence/synthesis/{shor,steane,rep3}_m_axi_fix_postroute_2026-08-20/, real Vivado reports, 2026-08-20.")
print(r"\begin{table}")
print(r"\centering")
print(r"\small")
print(r"\caption{Post-route resource utilisation and timing (real Vivado place-and-route "
      r"reports, not estimates), all three kernels with the \texttt{m\_axi} fix, part xcu55c, "
      r"300\,MHz target. All three achieved timing closure with zero failing endpoints out of "
      r"$\sim$427,000 each, and all three synthesised to zero post-route "
      r"BRAM\textsubscript{18K} (LUTRAM inference), a consistent pattern across independently "
      r"built kernels, not a one-off.}\label{tab:postroute}")
print(r"\begin{tabular}{lrrrrrr}")
print(r"\toprule")
print(r"\textbf{Kernel} & \textbf{BRAM} & \textbf{DSP} & \textbf{REG} & \textbf{LUT} & "
      r"\textbf{LUTAsMem} & \textbf{WNS (ns)} \\")
print(r"\midrule")
for name, bram, dsp, reg, lut, lutmem, wns in ROWS:
    print(f"{name} & {bram} & {dsp} & {reg} & {lut} & {lutmem} & {wns} \\\\")
print(r"\bottomrule")
print(r"\end{tabular}")
print(r"\end{table}")
