#!/usr/bin/env python3
"""Regenerate Table 2 (post-synthesis resource utilisation) from real
evidence/synthesis/*/*.rpt data, transcribed into table2_resources_data.yaml.

Addresses docs/CLAIMS_LEDGER.md C-030 through C-033 (R1-Min-5 adjacent):
every number here traces to an actual vitis_hls csynth_design run
(2026-08-19), not an estimate. Two variants are shown per kernel where both
exist (AXI-Lite only vs. with the m_axi output-buffer fix from B-001), so
the reader can see what that fix costs directly in the table rather than in
prose alone (ledger C-142-HLS).

Usage: python3 gen_table2.py > table2_resources.tex
"""

from pathlib import Path

try:
    import yaml
except ImportError:
    raise SystemExit("PyYAML required: pip install pyyaml")


def tex_escape(s: str) -> str:
    return s.replace("_", r"\_")


def main():
    data_path = Path(__file__).parent / "table2_resources_data.yaml"
    with open(data_path) as f:
        data = yaml.safe_load(f)

    kernels = data["kernels"]
    device = data["device"]

    print(r"% Auto-generated by paper/tables/gen_table2.py -- do not hand-edit.")
    print(r"% Source: evidence/synthesis/*/*.rpt, real vitis_hls csynth_design runs, 2026-08-19.")
    print(r"% Regenerate: python3 gen_table2.py > table2_resources.tex")
    print(r"\begin{table}")
    print(r"\centering")
    print(r"\caption{Post-synthesis resource utilisation (HLS-ESTIMATE, not post-route), "
          r"real \texttt{csynth\_design} runs, Vitis HLS 2023.2, 300\,MHz target. AXI-Lite-only "
          r"and \texttt{m\_axi}-augmented variants isolate the read-back fix's cost "
          r"(Section~\ref{sec:limitations}). Steane's kernel is a reconstruction "
          r"(Appendix~\ref{app:reconstruction}).}"
          r"\label{tab:resources}")
    print(r"\small")
    print(r"\setlength{\tabcolsep}{3pt}")
    print(r"\begin{tabular}{p{2.2cm}p{2.3cm}rrrrr}")
    print(r"\toprule")
    print(r"\textbf{Kernel} & \textbf{Variant} & \textbf{BRAM\textsubscript{18K}} & \textbf{DSP} "
          r"& \textbf{FF} & \textbf{LUT6} & \textbf{Lat.\ (cyc.)} \\")
    print(r"\midrule")
    for k in kernels:
        print(f"{tex_escape(k['name'])} & {tex_escape(k['variant'])} & {k['bram18k']} & "
              f"{k['dsp']} & {k['ff']} & {k['lut']} & {k['latency_cycles']} \\\\")
    print(r"\midrule")

    # Totals: the "as submitted" configuration (AXI-Lite only, matching what the
    # manuscript claims all three kernels use) -- excludes the m_axi variants,
    # which are a separate, labelled comparison, not part of the base total.
    axilite_rows = [k for k in kernels if "AXI-Lite only" in k["variant"]]
    total_bram = sum(k["bram18k"] for k in axilite_rows)
    total_dsp = sum(k["dsp"] for k in axilite_rows)
    total_ff = sum(k["ff"] for k in axilite_rows)
    total_lut = sum(k["lut"] for k in axilite_rows)
    print(f"\\textbf{{Total (AXI-Lite only)}} & & \\textbf{{{total_bram}}} & "
          f"\\textbf{{{total_dsp}}} & \\textbf{{{total_ff}}} & \\textbf{{{total_lut}}} & --- \\\\")
    print(f"U55C capacity & & {device['bram18k']:,} & {device['dsp']:,} & "
          f"{device['ff']:,} & {device['lut']:,} & --- \\\\")
    util_bram = 100 * total_bram / device["bram18k"]
    util_ff = 100 * total_ff / device["ff"]
    util_lut = 100 * total_lut / device["lut"]
    print(f"\\textbf{{Utilisation (\\%)}} & & {util_bram:.3f} & 0 & {util_ff:.3f} & "
          f"{util_lut:.3f} & --- \\\\")
    print(r"\bottomrule")
    print(r"\end{tabular}")
    print(r"\end{table}")


if __name__ == "__main__":
    main()
