#!/usr/bin/env python3
"""Table 3: post-route resource utilisation and timing, real Vivado reports.
Source: evidence/synthesis/shor_m_axi_fix_postroute_2026-08-20/. Shor kernel
(m_axi-fixed) only -- Rep-3 and Steane have not been through Vivado.
Usage: python3 gen_table3.py > table3_postroute.tex
"""
print(r"% Auto-generated by paper/tables/gen_table3.py -- do not hand-edit.")
print(r"% Source: evidence/synthesis/shor_m_axi_fix_postroute_2026-08-20/, real Vivado reports, 2026-08-20.")
print(r"\begin{table}")
print(r"\centering")
print(r"\caption{Post-route resource utilisation and timing (real Vivado place-and-route "
      r"reports, not estimates), Shor kernel with the \texttt{m\_axi} fix, part xcu55c, "
      r"300\,MHz target. Rep-3 and Steane have not been placed and routed; no row exists "
      r"for them.}\label{tab:postroute}")
print(r"\begin{tabular}{lr}")
print(r"\toprule")
print(r"\textbf{Metric} & \textbf{Value} \\")
print(r"\midrule")
print(r"BRAM\textsubscript{18K} & 0 \\")
print(r"DSP & 0 \\")
print(r"REG (FF) & 1245 \\")
print(r"LUT & 1018 \\")
print(r"LUTAsMem & 295 \\")
print(r"Worst negative slack (WNS) & +0.003\,ns \\")
print(r"Failing timing endpoints & 0 of 426{,}974 \\")
print(r"Achieved kernel clock & 300.000\,MHz \\")
print(r"\bottomrule")
print(r"\end{tabular}")
print(r"\end{table}")
