#!/usr/bin/env python3
"""Regenerate Table 2 (post-synthesis resource utilisation) from real
evidence/synthesis/*/*.rpt data, transcribed into table2_resources_data.yaml.

Addresses docs/CLAIMS_LEDGER.md C-030 through C-033 (R1-Min-5 adjacent):
every number here traces to an actual vitis_hls csynth_design run
(2026-08-19), not an estimate. Two variants are shown per kernel where both
exist (AXI-Lite only vs. with the m_axi output-buffer fix from B-001), so
the reader can see what that fix costs directly in the table rather than in
prose alone (ledger C-142-HLS).

Usage: python3 gen_table2.py > table2_resources.tex
"""

from pathlib import Path

try:
    import yaml
except ImportError:
    raise SystemExit("PyYAML required: pip install pyyaml")


def main():
    data_path = Path(__file__).parent / "table2_resources_data.yaml"
    with open(data_path) as f:
        data = yaml.safe_load(f)

    kernels = data["kernels"]
    device = data["device"]

    print(r"% Auto-generated by paper/tables/gen_table2.py -- do not hand-edit.")
    print(r"% Source: evidence/synthesis/*/*.rpt, real vitis_hls csynth_design runs, 2026-08-19.")
    print(r"% Regenerate: python3 gen_table2.py > table2_resources.tex")
    print(r"\begin{table}")
    print(r"\centering")
    print(r"\caption{Post-synthesis (HLS-ESTIMATE, not post-route) resource utilisation, "
          r"Vitis HLS 2023.2, part xcu55c-fsvh2892-2L-e, 300\,MHz target. Every row is a real "
          r"\texttt{csynth\_design} run (\texttt{evidence/synthesis/}), not an estimate. Two "
          r"variants are shown for Shor and Steane: AXI-Lite only (the architecture the "
          r"manuscript describes) and with the one-element \texttt{m\_axi} output-buffer "
          r"argument that unblocks hardware read-back (Section~\ref{sec:limitations}). Rep-3 "
          r"has not yet had the same fix applied. Steane's kernel is a from-source "
          r"reconstruction (no original source was recoverable; see "
          r"Appendix~\ref{app:reconstruction}), not the original submission's kernel.}"
          r"\label{tab:resources}")
    print(r"\begin{tabular}{llrrrrr}")
    print(r"\toprule")
    print(r"\textbf{Kernel} & \textbf{Variant} & \textbf{BRAM\textsubscript{18K}} & \textbf{DSP} "
          r"& \textbf{FF} & \textbf{LUT6} & \textbf{Latency (cyc.)} \\")
    print(r"\midrule")
    for k in kernels:
        print(f"{k['name']} & {k['variant']} & {k['bram18k']} & {k['dsp']} & {k['ff']} & "
              f"{k['lut']} & {k['latency_cycles']} \\\\")
    print(r"\midrule")

    # Totals: the "as submitted" configuration (AXI-Lite only, matching what the
    # manuscript claims all three kernels use) -- excludes the m_axi variants,
    # which are a separate, labelled comparison, not part of the base total.
    axilite_rows = [k for k in kernels if "AXI-Lite only" in k["variant"]]
    total_bram = sum(k["bram18k"] for k in axilite_rows)
    total_dsp = sum(k["dsp"] for k in axilite_rows)
    total_ff = sum(k["ff"] for k in axilite_rows)
    total_lut = sum(k["lut"] for k in axilite_rows)
    print(f"\\textbf{{Total (AXI-Lite only, all three)}} & & \\textbf{{{total_bram}}} & "
          f"\\textbf{{{total_dsp}}} & \\textbf{{{total_ff}}} & \\textbf{{{total_lut}}} & --- \\\\")
    print(f"U55C capacity & & {device['bram18k']:,} & {device['dsp']:,} & "
          f"{device['ff']:,} & {device['lut']:,} & --- \\\\")
    util_bram = 100 * total_bram / device["bram18k"]
    util_ff = 100 * total_ff / device["ff"]
    util_lut = 100 * total_lut / device["lut"]
    print(f"\\textbf{{Utilisation (\\%)}} & & {util_bram:.3f} & 0 & {util_ff:.3f} & "
          f"{util_lut:.3f} & --- \\\\")
    print(r"\bottomrule")
    print(r"\end{tabular}")
    print(r"\end{table}")


if __name__ == "__main__":
    main()
