#!/usr/bin/env python3
"""Regenerate Table 5 (LUT scalability) from table5_scalability_data.yaml.

Fixes R1-Maj-6: m = n - k applied consistently, CSS half-syndrome
decomposition (m_X | m_Z) shown explicitly for split-architecture codes,
and the surface-code rows disambiguated as rotated/unrotated
(docs/CLAIMS_LEDGER.md section E, C-040 through C-049).

Usage: python3 gen_table5.py > table5_lut_scaling.tex
Every number below is arithmetic on (n, k), not a measurement -- this
table carries no experimental claim, only a scalability projection.
"""

import math
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml")

BRAM18K_BITS = 18 * 1024  # 18 Kbit per BRAM18K primitive, capacity estimate only


def bram18k_cost(entries: int, width_bits: int, decoder_type: str = "") -> str:
    if decoder_type == "LUTRAM":
        return "0 (LUTRAM)"
    total_bits = entries * width_bits
    if total_bits <= 0:
        return "0"
    blocks = math.ceil(total_bits / BRAM18K_BITS)
    if blocks == 0:
        return "0 (LUTRAM)"
    if blocks > 300:
        return f"$>$300"
    return str(blocks)


def row_from_combined(code):
    n, k = code["n"], code["k"]
    m = n - k
    entries = 2 ** m
    width = 2 * n  # x_corr and z_corr packed together, as the Shor kernel does
    bram = "$\\infty$" if code.get("decoder_type") == "BP / MWPM" else bram18k_cost(entries, width, code["decoder_type"])
    entries_str = f"{entries:,}" if m <= 30 else f"$2^{{{m}}}$"
    return {
        "code": f"{code['name']} {code['label']}",
        "m": str(m),
        "entries": entries_str,
        "width": str(width),
        "bram": bram,
        "decoder": code["decoder_type"],
    }


def row_from_css_split(code):
    n, k = code["n"], code["k"]
    m = n - k
    m_x, m_z = code["m_x"], code["m_z"]
    assert m_x + m_z == m, f"{code['name']}: m_X+m_Z={m_x+m_z} != n-k={m}"
    entries_per_half = 2 ** m_x  # symmetric for Steane
    width = n  # one-hot correction, one LUT per half
    bram = bram18k_cost(2 * entries_per_half, width, code["decoder_type"])  # two halves
    return {
        "code": f"{code['name']} {code['label']}",
        "m": f"{m} ($m_X{{=}}{m_x} \\mid m_Z{{=}}{m_z}$)",
        "entries": f"2 $\\times$ {entries_per_half}",
        "width": str(width),
        "bram": bram,
        "decoder": code["decoder_type"],
    }


def main():
    data_path = Path(__file__).parent / "table5_scalability_data.yaml"
    with open(data_path) as f:
        data = yaml.safe_load(f)

    rows = []
    for code in data["codes"]:
        if code["architecture"] == "css-split":
            r = row_from_css_split(code)
        else:
            r = row_from_combined(code)
        if code.get("variant"):
            r["code"] += f" ({code['variant']})"
        rows.append(r)

    print(r"% Auto-generated by paper/tables/gen_table5.py -- do not hand-edit.")
    print(r"% m = n - k throughout (R1-Maj-6). Regenerate: python3 gen_table5.py")
    print(r"\begin{table}")
    print(r"\centering")
    print(r"\caption{LUT scalability, $m=n-k$ applied consistently. Steane shows its "
          r"$m_X\mid m_Z$ CSS half-syndrome split; surface-code rows disambiguate "
          r"rotated/unrotated. BRAM18K is a capacity-only estimate, not a synthesis "
          r"result.}\label{tab:lut-scaling}")
    print(r"\begin{tabular}{p{2.6cm}p{2.1cm}rrp{2.4cm}}")
    print(r"\toprule")
    print(r"\textbf{Code} & $m$ & \textbf{LUT entries} & \textbf{Width (bits)} & \textbf{BRAM18K / Decoder} \\")
    print(r"\midrule")
    for r in rows:
        print(f"{r['code']} & {r['m']} & {r['entries']} & {r['width']} & {r['bram']} / {r['decoder']} \\\\")
    print(r"\bottomrule")
    print(r"\end{tabular}")
    print(r"\end{table}")


if __name__ == "__main__":
    main()
