#!/usr/bin/env python3
"""Regenerate the Steane LUT/MWPM/UF two-proportion z-test table from real
data in experiments/E07b_montecarlo_software_mirror/processed/.
Usage: python3 gen_table_ztest.py > table_ztest.tex
"""
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DATA = (REPO_ROOT / "experiments" / "E07b_montecarlo_software_mirror" / "processed"
        / "montecarlo_processed.json")


def main():
    d = json.loads(DATA.read_text())
    z_tests = d["z_tests"]

    print(r"% Auto-generated by paper/tables/gen_table_ztest.py -- do not hand-edit.")
    print(r"\begin{table}")
    print(r"\centering")
    print(r"\caption{Two-proportion $z$-test $p$-values for the Steane kernel's three decoder "
          r"modes, IID-depolarising noise, $10^7$ shots per point per mode. All comparisons "
          r"non-significant at $\alpha=0.05$ except one, itself consistent with the expected "
          r"false-positive rate across 27 simultaneous comparisons.}\label{tab:ztest}")
    print(r"\begin{tabular}{lrrr}")
    print(r"\toprule")
    print(r"\textbf{$p$} & \textbf{LUT vs.\ MWPM} & \textbf{LUT vs.\ UF} & \textbf{MWPM vs.\ UF} \\")
    print(r"\midrule")
    for row in z_tests:
        flag = lambda v: f"{v:.4f}" + ("$^*$" if v < 0.05 else "")
        print(f"{row['p']:g} & {flag(row['pval_LUT_vs_MWPM'])} & {flag(row['pval_LUT_vs_UF'])} "
              f"& {flag(row['pval_MWPM_vs_UF'])} \\\\")
    print(r"\bottomrule")
    print(r"\end{tabular}")
    print(r"\end{table}")


if __name__ == "__main__":
    main()
